- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get VPC variables
      include_vars: variables/setup_for_vpc.txt

    - name: Create VPC
      ec2_vpc_net:
        name: "{{ans-test-vpc}}"
        cidr_block: "{{vpcCidr}}"
        region: "{{region}}"
        dns_support: yes
        dns_hostnames: yes
        tenancy: default
        state: "{{state}}"
      register: vpcout